app: Add async support for callback
named-data/python-ndn pull request #43
Opened 2022-03-03 03:01 UTC by GlassyYang

`python-ndn` is writen by coroutine, **but** app doesn't support async function register, which means if a user-registered callback function is a timing consuming operation, it will still block everything. under this situation, `async callback register` is extreamily useful.

2022-03-03 04:04 UTC, yoursunny requested changes
Modify `Route` type declaration so that the callable can return Awaitable in addition to None.

Add or modify unit test for the new feature.

Update the copyright end year in each modified file.

2022-03-03 10:14 UTC, zjkmxy commented
See #16 
This design is on purpose: the producer must respond to the Interest first before it performs any operation that takes time.

2022-03-03 11:52 UTC, GlassyYang commented
Should we ensure whether interest is not expired or not like this way: we just sleep a certain time, and cancel the task when it is still run.
with async function, we can tell user their callback takes too long rather than let user debug and find this problem by themself.

2022-03-03 19:54 UTC, zjkmxy commented
You can use `create_task` to do whatever you want. There is no need to modify the library.
An async callback delays not only this packet but also blocks all future packets.

2022-03-04 01:54 UTC, GlassyYang commented
That's remind me. Thank you very much.

2022-03-04 01:54 UTC, closed without merging